---
name: Build & publish docker images

"on":
  workflow_dispatch:
  release:
    types:
      - released
      - prereleased

permissions:
  contents: read

env:
  REGISTRY: docker.io
  REGISTRY_ACCOUNT: wydler
  REGISTRY_REPO: mediathekview
  REGISTRY_REPO_TAG_CACHE_NAME: buildcache
  REGISTRY_PLATFORMS: linux/amd64

jobs:
  setup-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435  # v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create tag list for docker image
        id: tags
        run: |
          if [ "${{ github.event.release.prerelease }}" = true ]; then
            echo "docker=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [ ! -z "${{ github.event.release.tag_name }}" ]; then
            echo "docker=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:latest, ${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "docker=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
        with:
          context: ./mediathekview/docker/
          push: true
          tags: ${{ steps.tags.outputs.docker }}
          platforms: ${{ env.REGISTRY_PLATFORMS }}
          cache-from: type=registry,ref=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ env.REGISTRY_REPO_TAG_CACHE_NAME }}
          cache-to: type=registry,ref=${{ env.REGISTRY_ACCOUNT }}/${{ env.REGISTRY_REPO }}:${{ env.REGISTRY_REPO_TAG_CACHE_NAME }},mode=max
