---
name: Tools - Docker Build Test

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
    paths:
      - '**Dockerfile'

permissions:
  contents: read

env:
  REGISTRY_PLATFORMS: ${{ vars.REGISTRY_PLATFORMS }}

jobs:
  docker-build-image:
    name: Docker Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435  # v3.11.1

      - name: Build docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
        with:
          context: .
          file: ./mediathekview/docker/Dockerfile
          push: false
          platforms: ${{ env.REGISTRY_PLATFORMS }}
